set -g default-terminal "xterm-ghostty"
set -ga terminal-overrides ",xterm-ghostty:Tc"

set -g window-style 'fg=default,bg=default'
set -g window-active-style 'fg=default,bg=default'

set -g pane-active-border-style "fg=yellow,bg=default"
set -g pane-border-style "fg=white"

set -g status-style "bg=yellow,fg=black"

set -g mouse on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind C-b
set-option -g prefix C-b
bind-key C-m send-prefix

unbind '"'
unbind %
unbind w

bind w new-window
bind W choose-window

bind t split-window -h
bind T split-window -v
